package com.picc.riskctrl.common.proxy.vo;

// Generated by Hibernate Tools 3.2.0.b9 (sinosoft version)

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * PrpDplan generated by Tools.Don't edit.
 */
//@Entity
//@Table(name = "prpdplan")
@Data
public class PrpDplan implements Serializable {

    /** 方案代码 */
    private String planCode;
    /** 方案类型代码 */
    private String planTypeCode;
    /** 旧方案代码 */
    private String oldPlanCode;
    /** 方案简体中文名称 */
    private String planCName;
    /** 方案繁体中文名称 */
    private String planTName;
    /** 方案简称名称 */
    private String planSName;
    /** 方案英文名称 */
    private String planEName;
    /** 是否定额 */
    private String isFixedFlag;
    /** 框架代码 */
    private String frameCode;
    /** 框架名称 */
    private String frameCName;
    /** 产品代码 */
    private String riskCode;
    /** 产品名称 */
    private String riskCName;
    /** 产品属性 */
    private String riskAttribute;
    /** 销售区域层级 */
    private String saleAreaLevel;
    /** 销售区域代码;	用逗号分隔 */
    private String businessArea;
    /** 销售区域名称;	用逗号分隔 */
    private String businessName;
    /** 方案是否可修改 */
    private String updateFlag;
    /** 出单方案时是否一份 */
    private String uniqueFlag;
    /** 方案允许最大份数 */
    private String maxCount;
    /** 文本内容（预留） */
    private String ContentNumber;
    /** 创建人 */
    private String creatorCode;
    /** 修改人 */
    private String updaterCode;
    /**  */
    private String contentNumber;
    /** 方案维度 */
    private String dimensions;
    /** 方案维度类型 */
    private String dimensionLower;
    /**  */
    private String dimensionUpper;
    /** 维度标志*/
    private String dimensionRemark;
    /** 生效日期 */
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date validDate;
    /** 失效日期 */
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date invalidDate;
    /** 有效标志 */
    private String validStatus;
    /** 适用系统（tcol1） */
    private String platformtype;
    /** 备注 */
    private String remark;
    /** 同步标志 */
    private String synflag;
    /** 标志字段 */
    private String flag;
    /** 是否是家庭保额产品*/
    private String isFamilyAmount;
//	/** 插入时间 */
//	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
//	private Date insertTimeForHis;
//	/** 更新时间 */
//	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
//	private Date operateTimeForHis;
    /**
     * --**业务来源
     * --**0：传统直销业务
     * --**1：个人代理业务
     * --**2:专业代理业务
     * --**3:兼业代理业务
     * --**4:经纪业务
     * --**5:新渠道直销业务
     */
    private String agentType;
    /**
     *                 "cpzxDrisk": null,
     *                 "cpzxDclass": null,
     *                 "cpzxPlanType": null,
     *                 "cpzxDplanClauseKinds": null,
     *                 "cpzxDplanLimits": null,
     *                 "cpzxDplanEngages": null
     */


    public PrpDplan() {
    }

//	/**
//	 * ��������
//	 */
//	@Id
//	@Column(name = "plancode")
//	public String getPlanCode() {
//		return this.planCode;
//	}
//
//	public void setPlanCode(String planCode) {
//		this.planCode = planCode;
//	}
//
//	@Column(name = "plantypecode")
//	public String getPlanTypeCode() {
//		return planTypeCode;
//	}
//
//	public void setPlanTypeCode(String planTypeCode) {
//		this.planTypeCode = planTypeCode;
//	}
//
//	/**
//	 * �ɷ�������
//	 */
//
//	@Column(name = "oldplancode")
//	public String getOldPlanCode() {
//		return this.oldPlanCode;
//	}
//
//	public void setOldPlanCode(String oldPlanCode) {
//		this.oldPlanCode = oldPlanCode;
//	}
//
//	/**
//	 * ���������������
//	 */
//
//	@Column(name = "plancname")
//	public String getPlanCName() {
//		return this.planCName;
//	}
//
//	public void setPlanCName(String planCName) {
//		this.planCName = planCName;
//	}
//
//	/**
//	 * ���������������
//	 */
//
//	@Column(name = "plantname")
//	public String getPlanTName() {
//		return this.planTName;
//	}
//
//	public void setPlanTName(String planTName) {
//		this.planTName = planTName;
//	}
//
//	/**
//	 * ����������
//	 */
//
//	@Column(name = "plansname")
//	public String getPlanSName() {
//		return this.planSName;
//	}
//
//	public void setPlanSName(String planSName) {
//		this.planSName = planSName;
//	}
//
//	/**
//	 * ����Ӣ�����
//	 */
//
//	@Column(name = "planename")
//	public String getPlanEName() {
//		return this.planEName;
//	}
//
//	public void setPlanEName(String planEName) {
//		this.planEName = planEName;
//	}
//
//	/**
//	 * �Ƿ񶨶�
//	 */
//
//	@Column(name = "isfixedflag")
//	public String getIsFixedFlag() {
//		return this.isFixedFlag;
//	}
//
//	public void setIsFixedFlag(String isFixedFlag) {
//		this.isFixedFlag = isFixedFlag;
//	}
//
//	/**
//	 * ��ܴ���
//	 */
//
//	@Column(name = "framecode")
//	public String getFrameCode() {
//		return this.frameCode;
//	}
//
//	public void setFrameCode(String frameCode) {
//		this.frameCode = frameCode;
//	}
//
//	/**
//	 * ��Ʒ����
//	 */
//
//	@Column(name = "riskcode")
//	public String getRiskCode() {
//		return this.riskCode;
//	}
//
//	public void setRiskCode(String riskCode) {
//		this.riskCode = riskCode;
//	}
//
//	/**
//	 * ��Ʒ����
//	 */
//
//	@Column(name = "riskattribute")
//	public String getRiskAttribute() {
//		return this.riskAttribute;
//	}
//
//	public void setRiskAttribute(String riskAttribute) {
//		this.riskAttribute = riskAttribute;
//	}
//
//	/**
//	 * ��������㼶
//	 */
//
//	@Column(name = "salearealevel")
//	public String getSaleAreaLevel() {
//		return this.saleAreaLevel;
//	}
//
//	public void setSaleAreaLevel(String saleAreaLevel) {
//		this.saleAreaLevel = saleAreaLevel;
//	}
//
//	/**
//	 * �����������(�ö��ŷָ�)
//	 */
//
//	@Column(name = "saleareacode")
//	@Basic(fetch = FetchType.LAZY)
//	@Type(type = "org.springframework.orm.hibernate3.support.ClobStringType")
//	public String getSaleAreaCode() {
//		return this.saleAreaCode;
//	}
//
//	public void setSaleAreaCode(String saleAreaCode) {
//		this.saleAreaCode = saleAreaCode;
//	}
//
//	/**
//	 * ����������???(�ö��ŷָ�)
//	 */
//
//	@Column(name = "saleareaname")
//	@Basic(fetch = FetchType.LAZY)
//	@Type(type = "org.springframework.orm.hibernate3.support.ClobStringType")
//	public String getSaleAreaName() {
//		return this.saleAreaName;
//	}
//
//	public void setSaleAreaName(String saleAreaName) {
//		this.saleAreaName = saleAreaName;
//	}
//
//	/**
//	 * �����Ƿ���޸�
//	 */
//
//	@Column(name = "updateflag")
//	public String getUpdateFlag() {
//		return this.updateFlag;
//	}
//
//	public void setUpdateFlag(String updateFlag) {
//		this.updateFlag = updateFlag;
//	}
//
//	/**
//	 * ��������ʱ�Ƿ�һ��
//	 */
//
//	@Column(name = "uniqueflag")
//	public String getUniqueFlag() {
//		return this.uniqueFlag;
//	}
//
//	public void setUniqueFlag(String uniqueFlag) {
//		this.uniqueFlag = uniqueFlag;
//	}
//
//	/**
//	 * ������
//	 */
//
//	@Column(name = "maxCount")
//	public String getMaxCount() {
//		return this.maxCount;
//	}
//
//	public void setMaxCount(String maxCount) {
//		this.maxCount = maxCount;
//	}
//
//	/**
//	 * ������
//	 */
//
//	@Column(name = "creatercode")
//	public String getCreaterCode() {
//		return this.createrCode;
//	}
//
//	public void setCreaterCode(String createrCode) {
//		this.createrCode = createrCode;
//	}
//
//	/**
//	 * ����ʱ��
//	 */
//	@Temporal(TemporalType.DATE)
//	@Column(name = "createtime")
//	public Date getCreateTime() {
//		return this.createTime;
//	}
//
//	public void setCreateTime(Date createTime) {
//		this.createTime = createTime;
//	}
//
//	/**
//	 * ����޸���
//	 */
//
//	@Column(name = "updatercode")
//	public String getUpdaterCode() {
//		return this.updaterCode;
//	}
//
//	public void setUpdaterCode(String updaterCode) {
//		this.updaterCode = updaterCode;
//	}
//
//	/**
//	 * ����޸�ʱ��
//	 */
//	@Temporal(TemporalType.DATE)
//	@Column(name = "updatetime")
//	public Date getUpdateTime() {
//		return this.updateTime;
//	}
//
//	public void setUpdateTime(Date updateTime) {
//		this.updateTime = updateTime;
//	}
//
//	/**
//	 * �ı����ݣ�Ԥ����
//	 */
//
//	@Column(name = "contentnumber")
//	public String getContentNumber() {
//		return this.contentNumber;
//	}
//
//	public void setContentNumber(String contentNumber) {
//		this.contentNumber = contentNumber;
//	}
//
//	/**
//	 * ��Ч����
//	 */
//	@Temporal(TemporalType.DATE)
//	@Column(name = "validdate")
//	public Date getValidDate() {
//		return this.validDate;
//	}
//
//	public void setValidDate(Date validDate) {
//		this.validDate = validDate;
//	}
//
//	/**
//	 * ʧЧ����
//	 */
//	@Temporal(TemporalType.DATE)
//	@Column(name = "invaliddate")
//	public Date getInvalidDate() {
//		return this.invalidDate;
//	}
//
//	public void setInvalidDate(Date invalidDate) {
//		this.invalidDate = invalidDate;
//	}
//
//	/**
//	 * ��Ч��־
//	 */
//
//	@Column(name = "validind")
//	public String getValidInd() {
//		return this.validInd;
//	}
//
//	public void setValidInd(String validInd) {
//		this.validInd = validInd;
//	}
//
//	/**
//	 * Ԥ���ֶ�1
//	 */
//
//	@Column(name = "tcol1")
//	public String getTcol1() {
//		return this.tcol1;
//	}
//
//	public void setTcol1(String tcol1) {
//		this.tcol1 = tcol1;
//	}
//
//	/**
//	 * Ԥ���ֶ�2
//	 */
//
//	@Column(name = "tcol2")
//	public String getTcol2() {
//		return this.tcol2;
//	}
//
//	public void setTcol2(String tcol2) {
//		this.tcol2 = tcol2;
//	}
//
//	/**
//	 * Ԥ���ֶ�3
//	 */
//
//	@Column(name = "tcol3")
//	public String getTcol3() {
//		return this.tcol3;
//	}
//
//	public void setTcol3(String tcol3) {
//		this.tcol3 = tcol3;
//	}
//
//	/**
//	 * ��ע
//	 */
//
//	@Column(name = "remark")
//	@Basic(fetch = FetchType.LAZY)
//	@Type(type = "org.springframework.orm.hibernate3.support.ClobStringType")
//	public String getRemark() {
//		return this.remark;
//	}
//
//	public void setRemark(String remark) {
//		this.remark = remark;
//	}
//
//	/**
//	 * ��־�ֶ�
//	 */
//
//	@Column(name = "flag")
//	public String getFlag() {
//		return this.flag;
//	}
//
//	public void setFlag(String flag) {
//		this.flag = flag;
//	}
//
//	public String getDimensions() {
//		return dimensions;
//	}
//
//	public void setDimensions(String dimensions) {
//		this.dimensions = dimensions;
//	}
//
//	public String getDimensionRemark() {
//		return dimensionRemark;
//	}
//
//	public void setDimensionRemark(String dimensionRemark) {
//		this.dimensionRemark = dimensionRemark;
//	}
//
//	public static long getSerialVersionUID() {
//		return serialVersionUID;
//	}
//	/**
//	 * 是否是家庭保额产品
//	 */
//	@Column(name="isfamilyamount")
//	public String getIsFamilyAmount() {
//		return isFamilyAmount;
//	}
//
//	public void setIsFamilyAmount(String isFamilyAmount) {
//		this.isFamilyAmount = isFamilyAmount;
//	}

}
